name: Run Robot Framework Tests with Playwright

on:
  pull_request:
    branches:
      - main  # Defina a branch alvo para o PR

jobs:
  test:
    runs-on: ubuntu-latest  # Ambiente Linux

    steps:
      # Passo 1: Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v2

      # Passo 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Passo 3: Instalar dependências Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-browser
          pip install robotframework-debuglibrary
          pip install pyyaml

      # Passo 4: Instalar dependências do sistema operacional
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-0 \
            libgbm-dev \
            libnss3 \
            libasound2 \
            libxshmfence1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libdrm2 \
            libxfixes3 \
            libxcursor1 \
            libxinerama1 \
            libpango-1.0-0 \
            libcups2

      # Passo 5: Instalar Playwright e inicializar o Browser
      - name: Install Playwright and Init Browser
        run: |
          playwright install --with-deps
          rfbrowser init  # Inicializa o navegador Playwright para Robot Framework

      # Passo 6: Rodar os testes
      - name: Run Robot Framework Tests
        run: |
          robot .  # Roda todos os testes

      # Passo 7: Upload dos resultados dos testes
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: result.xml  # Arquivo XML do relatório de testes
