name: Run Robot Framework Tests with Playwright

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-browser
          pip install robotframework-debuglibrary
          pip install pyyaml

      - name: Update package list
        run: sudo apt-get update

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-0 \
            libgbm-dev \
            libnss3 \
            libxshmfence1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libdrm2 \
            libxfixes3 \
            libxcursor1 \
            libxinerama1 \
            libpango-1.0-0 \
            libcups2 \
            alsa-utils  # Alternativa para libasound2

      - name: Install Playwright and Init Browser
        run: |
          playwright install --with-deps
          rfbrowser init

      - name: Run Robot Framework Tests
        run: |
          robot .

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: result.xml
