name: Run Robot Framework Tests with Playwright

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-browser
          pip install robotframework-debuglibrary
          pip install pyyaml
          pip install invoke

      - name: Install Playwright Browsers
        run: |
          rfbrowser init  # Instala os navegadores do Playwright

      - name: Run Robot Framework Tests
        run: |
          invoke ci

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: |
            result.xml
            log.html
            report.html
