name: Run Robot Framework Tests with Playwright

on:
  pull_request:
    branches:
      - main  # Defina a branch alvo para o PR (por exemplo, `main`)

jobs:
  test:
    runs-on: ubuntu-latest  # Pode ser `ubuntu-latest`, `windows-latest`, ou `macos-latest`
    
    steps:
      # Passo 1: Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v2

      # Passo 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework  # Instala o Robot Framework
          pip install robotframework-browser  # Instala o Robot Framework com o Playwright
          pip install robotframework-debuglibrary  # Instala o DebugLibrary
          pip install pyyaml  # Instala o PyYAML

      # Passo 4: Inicializar o Browser (Playwright) em modo headless
      - name: Initialize Playwright Browser in headless mode
        run: |
          export HEADLESS=true  # Variável de ambiente para garantir modo headless
          rfbrowser init  # Inicializa o navegador com Playwright

      # Passo 5: Rodar os testes
      - name: Run Robot Framework Tests
        run: |
          robot --include testes testes.robot  # Comando para rodar seus testes

      # Passo 6: Verificar os resultados (opcional)
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: result.xml  # Se você gerar um arquivo XML com o resultado, como um relatório de testes
