name: Run Robot Framework Tests with Playwright

on:
  pull_request:
    branches:
      - main  # Defina a branch alvo para o PR

jobs:
  test:
    runs-on: ubuntu-latest  # Ambiente Linux

    steps:
      # Passo 1: Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v2

      # Passo 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Passo 3: Instalar dependências Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-browser
          pip install robotframework-debuglibrary
          pip install pyyaml

      # Passo 4: Instalar dependências do Playwright
      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-dev \
            libgraphene-1.0-0 \
            libwoff1 \
            libwoff2-1 \
            libvpx7 \
            libevent-2.1-7 \
            libopus0 \
            libgstallocators-1.0-0 \
            libgstapp-1.0-0 \
            libgstpbutils-1.0-0 \
            libgstaudio-1.0-0 \
            libgstgl-1.0-0 \
            libgsttag-1.0-0 \
            libgstvideo-1.0-0 \
            libgstcodecparsers-1.0-0 \
            libgstfft-1.0-0 \
            libflite1 \
            libflite-usenglish1 \
            libflite-cmu-grapheme-lang1 \
            libflite-cmu-grapheme-lex1 \
            libflite-cmu-indic-lang1 \
            libflite-cmu-indic-lex1 \
            libflite-cmulex1 \
            libflite-cmu-time-awb1 \
            libflite-cmu-us-awb1 \
            libflite-cmu-us-kal16-1 \
            libflite-cmu-us-kal1 \
            libflite-cmu-us-rms1 \
            libflite-cmu-us-slt1 \
            libavif13 \
            libharfbuzz-icu0 \
            libsecret-1-0 \
            libhyphen0 \
            libmanette-0.2-0 \
            libgles2 \
            libx264-164

      # Passo 5: Instalar Playwright e inicializar o Browser
      - name: Initialize Playwright
        run: |
          playwright install --with-deps
          rfbrowser init  # Inicializa o navegador Playwright para Robot Framework

      # Passo 6: Rodar os testes
      - name: Run Robot Framework Tests
        run: |
          robot .  # Roda todos os testes

      # Passo 7: Upload dos resultados dos testes
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: result.xml  # Arquivo XML do relatório de testes
